version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redbut_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data: