-- Insert sample menu items data
INSERT INTO "menu_items" (
  "id",
  "category", 
  "name",
  "description",
  "image",
  "price",
  "status",
  "video",
  "served_info",
  "available_options",
  "available_extras",
  "created_at",
  "updated_at"
) VALUES
  -- Appetizers
  (
    gen_random_uuid(),
    'Appetizers',
    'Bruschetta al Pomodoro',
    'Grilled bread rubbed with garlic and topped with fresh tomatoes, basil, and olive oil.',
    'https://images.unsplash.com/photo-1505253716362-af2422276571',
    9.50,
    'Active',
    NULL,
    'Served as a set of 4 pieces.',
    '["vegetarian", "vegan_option"]'::jsonb,
    '["extra_basil", "add_feta_cheese"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Appetizers',
    'Crispy Calamari',
    'Lightly battered and fried calamari served with a zesty marinara sauce.',
    'https://images.unsplash.com/photo-1599043513900-ed6e00c93e1f',
    13.75,
    'Active',
    NULL,
    'Served with a lemon wedge.',
    '["seafood"]'::jsonb,
    '["extra_marinara_sauce", "spicy_aioli"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Soups
  (
    gen_random_uuid(),
    'Soups',
    'Tomato Basil Soup',
    'Creamy tomato soup infused with fresh basil.',
    'https://images.unsplash.com/photo-1575663401309-555775514802',
    7.00,
    'Active',
    NULL,
    'Served with a side of garlic bread.',
    '["vegetarian", "gluten_free"]'::jsonb,
    '["add_cheese_croutons"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Main Course - Pizza (already have Margherita)
  (
    gen_random_uuid(),
    'Main Course',
    'Pepperoni Pizza',
    'Classic pizza with rich tomato sauce, mozzarella, and spicy pepperoni slices.',
    'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee',
    16.50,
    'Active',
    NULL,
    'Available in 12-inch size.',
    '["meat"]'::jsonb,
    '["extra_cheese", "add_mushrooms", "add_olives"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Main Course - Pasta
  (
    gen_random_uuid(),
    'Main Course',
    'Spaghetti Carbonara',
    'Classic Italian pasta with eggs, Pecorino Romano cheese, pancetta, and black pepper.',
    'https://images.unsplash.com/photo-1588013273468-31508b965b27',
    17.00,
    'Active',
    NULL,
    'Made with fresh, homemade pasta.',
    '["classic_italian"]'::jsonb,
    '["extra_pancetta", "add_garlic"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Main Course',
    'Lasagna Bolognese',
    'Layers of fresh pasta, rich meat sauce, béchamel, and Parmesan cheese, baked to perfection.',
    'https://images.unsplash.com/photo-1574894709920-FE25b073772b',
    19.50,
    'Active',
    NULL,
    'A hearty portion, served bubbling hot.',
    '["comfort_food", "meat"]'::jsonb,
    '["extra_cheese_layer"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Main Course - Seafood
  (
    gen_random_uuid(),
    'Main Course',
    'Grilled Salmon',
    'Fresh Atlantic salmon fillet, grilled and served with a lemon-dill sauce.',
    'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2',
    24.00,
    'Active',
    NULL,
    'Served with roasted asparagus and quinoa.',
    '["healthy", "seafood", "gluten_free"]'::jsonb,
    '["extra_sauce", "side_salad_instead_of_quinoa"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Main Course - Vegetarian
  (
    gen_random_uuid(),
    'Main Course',
    'Vegetable Stir-Fry',
    'A medley of fresh seasonal vegetables stir-fried in a savory soy-ginger sauce, served with steamed rice.',
    'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3', -- Placeholder image
    15.50,
    'Active',
    NULL,
    'Can be made spicy upon request.',
    '["vegetarian", "vegan", "healthy"]'::jsonb,
    '["add_tofu", "brown_rice_option"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Desserts (already have Chocolate Cake)
  (
    gen_random_uuid(),
    'Desserts',
    'Tiramisu',
    'Classic Italian dessert made with ladyfingers dipped in coffee, layered with a whipped mixture of eggs, sugar, and mascarpone cheese, flavored with cocoa.',
    'https://images.unsplash.com/photo-1571877276128-3925a793dd23',
    9.50,
    'Active',
    NULL,
    'Dusted with cocoa powder.',
    '["vegetarian", "classic_italian", "contains_coffee"]'::jsonb,
    '["extra_cocoa_powder"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Desserts',
    'Apple Pie',
    'Warm apple pie with a flaky crust, served with a scoop of vanilla ice cream.',
    'https://images.unsplash.com/photo-1562538242-1350535913c2',
    8.00,
    'Active',
    NULL,
    'Can be served with caramel sauce.',
    '["vegetarian", "comfort_food"]'::jsonb,
    '["add_caramel_sauce", "extra_ice_cream_scoop"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Beverages - Non-alcoholic (already have Orange Juice, Espresso)
  (
    gen_random_uuid(),
    'Beverages',
    'Sparkling Water',
    'Chilled sparkling mineral water.',
    'https://images.unsplash.com/photo-1556881105-699df7a17fcc',
    3.00,
    'Active',
    NULL,
    'Served with a slice of lemon or lime.',
    '["refreshing", "zero_calorie"]'::jsonb,
    '["add_lemon", "add_lime"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Beverages',
    'Iced Tea',
    'Freshly brewed iced tea, available sweetened or unsweetened.',
    'https://images.unsplash.com/photo-1556745753-b2904692b3cd',
    3.50,
    'Active',
    NULL,
    'Choice of lemon or peach flavor.',
    '["refreshing"]'::jsonb,
    '["sweetened", "unsweetened", "lemon_flavor", "peach_flavor"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Beverages - Alcoholic (Example)
  (
    gen_random_uuid(),
    'Beverages',
    'House Red Wine',
    'A glass of our carefully selected house red wine.',
    'https://images.unsplash.com/photo-1584916201218-f4242ceb4809',
    7.50,
    'Active',
    NULL,
    'Available by the glass or bottle.',
    '["alcoholic", "red_wine"]'::jsonb,
    '["bottle_option"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  -- Existing items from user prompt, slightly modified for consistency
  (
    gen_random_uuid(),
    'Appetizers',
    'Margherita Pizza (Original)', -- Renamed to avoid conflict if IDs are different
    'Traditional pizza with tomatoes, mozzarella cheese, and basil',
    'https://images.unsplash.com/photo-1574071318508-1cdbab80d002',
    14.99,
    'Active',
    NULL,
    'Served hot with fresh basil',
    '["vegetarian"]'::jsonb,
    '["extra_cheese", "extra_basil"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Appetizers',
    'Caesar Salad (Original)',
    'Fresh romaine lettuce with parmesan cheese and caesar dressing',
    'https://images.unsplash.com/photo-1551248429-40975aa4de74',
    12.50,
    'Active',
    NULL,
    'Served with homemade croutons',
    '["vegetarian", "gluten_free_option"]'::jsonb,
    '["extra_parmesan", "grilled_chicken"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Main Course',
    'Grilled Chicken Breast (Original)',
    'Juicy grilled chicken breast with herbs and spices',
    'https://images.unsplash.com/photo-1532550907401-a500c9a57435',
    18.99,
    'Active',
    NULL,
    'Served with choice of side',
    '["gluten_free", "protein_rich"]'::jsonb,
    '["extra_sauce", "double_portion"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Main Course', 
    'Beef Burger (Original)',
    'Juicy beef patty with lettuce, tomato, and special sauce',
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    16.50,
    'Active',
    NULL,
    'Served with french fries',
    '["popular"]'::jsonb,
    '["extra_patty", "bacon", "cheese"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Desserts',
    'Chocolate Cake (Original)',
    'Rich chocolate cake with chocolate ganache',
    'https://images.unsplash.com/photo-1578985545062-69928b1d9587',
    8.99,
    'Active',
    NULL,
    'Served with vanilla ice cream',
    '["vegetarian", "sweet"]'::jsonb,
    '["extra_ice_cream", "whipped_cream"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Beverages',
    'Fresh Orange Juice (Original)',
    'Freshly squeezed orange juice',
    'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b',
    4.50,
    'Active',
    NULL,
    'Served chilled',
    '["fresh", "vitamin_c", "no_sugar_added"]'::jsonb,
    '["extra_pulp", "ice"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Beverages',
    'Espresso Coffee (Original)',
    'Strong Italian espresso coffee',
    'https://images.unsplash.com/photo-1511920170033-f8396924c348',
    3.50,
    'Active',
    NULL,
    'Served hot in espresso cup',
    '["caffeinated", "italian_style"]'::jsonb,
    '["extra_shot", "sugar", "milk"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid(),
    'Main Course',
    'Peri-Peri Chicken (Original)',
    'Spicy grilled chicken with peri-peri sauce',
    'https://images.unsplash.com/photo-1598103442097-8b74394b95c6',
    19.99,
    'Active',
    NULL,
    'Served with rice and vegetables',
    '["spicy", "peri_peri", "gluten_free"]'::jsonb,
    '["extra_spicy", "mild_sauce", "extra_rice"]'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );
